name: DBT Pipeline
on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["F1 Pipeline"]
  #   types:
  #     - completed

jobs:
  dbt:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Create profiles.yml
        run: |
          cat > f1_data/profiles.yml << 'EOF'
f1_data:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('SUPABASE_HOST') }}"
      user: "{{ env_var('SUPABASE_USER') }}"
      password: "{{ env_var('SUPABASE_PASSWORD') }}"
      port: "{{ env_var('SUPABASE_PORT') | int }}"
      dbname: "{{ env_var('SUPABASE_DBNAME') }}"
      schema: raw
      threads: 4
EOF:

      - name: Install dbt dependencies
        working-directory: f1_data
        run: dbt deps --profiles-dir .

      - name: dbt debug
        working-directory: f1_data
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_DBNAME: ${{ secrets.SUPABASE_DBNAME }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        run: dbt debug --profiles-dir .

      - name: Run dbt build
        working-directory: f1_data
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_DBNAME: ${{ secrets.SUPABASE_DBNAME }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        run: dbt run --profiles-dir . --select models/staging/